version: "3"
services:

  api-db:
    image: "postgres:14"
    container_name: "api_pg"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - "5432:5432"
    volumes:
      - "api-postgres:/var/lib/postgresql/data"
    restart: always

volumes:
  api-postgres:
